export const RETRIEVE_VEHICLES = "RETRIEVE_VEHICLES";
export const CREATE_VEHICLE = "CREATE_VEHICLE";
export const RETRIEVE_VEHICLE = "RETRIEVE_VEHICLE";
export const DELETE_VEHICLE = "DELETE_VEHICLE";
export const FILTER_VEHICLE = "FILTER_VEHICLE";